version: '3.8'

services:
  telegram-bot:
    image: s21_community-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5555:5555"
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      SCHOOL_USERNAME: ${SCHOOL_USERNAME}
      SCHOOL_PASSWORD: ${SCHOOL_PASSWORD}
      ROCKET_CHAT_PASSWORD: ${ROCKET_CHAT_PASSWORD}
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:17-alpine3.20
    container_name: community-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    restart: always

volumes:
  postgres_data: