bot:
    token: systemEnvironment['BOT_TOKEN']
    username: systemEnvironment['BOT_NAME']
school:
    password: systemEnvironment['SCHOOL_PASSWORD']
    username: systemEnvironment['SCHOOL_USERNAME']
server:
    port: 5555
spring:
    datasource:
        password: systemEnvironment['DB_PASSWORD']
        url: jdbc:postgresql://147.45.42.229:5432/CommunityDatabase
        username: systemEnvironment['DB_USER']
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
#    liquibase:
#        change-log: db/changelog/main-changelog.yaml
